"""
GitHub Integration — creates fix PRs and posts review comments
using the PyGithub library.
"""

import os
from dataclasses import dataclass
from datetime import datetime

from github import Github, GithubException
from dotenv import load_dotenv

from doc_checker.repairer import RepairResult, ConfidenceLevel

load_dotenv()


# ── Data models ────────────────────────────────────────────────────────────────

@dataclass
class ActionOutput:
    """Summary of everything the action did on this PR run."""
    pr_number: int
    sections_checked: int
    sections_accurate: int
    sections_autofix: int        # high confidence, PR created
    sections_flagged: int        # low confidence, comment posted
    fix_pr_numbers: list[int]    # PRs created for auto-fixes
    comment_url: str             # URL of the summary comment posted


# ── PR creator ─────────────────────────────────────────────────────────────────

class GitHubIntegration:
    """
    Handles all GitHub API interactions:
    - Creating fix branches and PRs for high-confidence repairs
    - Posting review comments on the original PR for low-confidence flags
    - Posting a summary comment on every run
    """

    def __init__(self):
        token = os.getenv("GITHUB_TOKEN")
        repo_name = os.getenv("GITHUB_REPOSITORY")  # e.g. "owner/repo"

        if not token:
            raise ValueError("GITHUB_TOKEN not set")
        if not repo_name:
            raise ValueError("GITHUB_REPOSITORY not set")

        self.gh = Github(token)
        self.repo = self.gh.get_repo(repo_name)
        print(f"[GitHub] Connected to {repo_name}")

    def process_repairs(
        self,
        repairs: list[RepairResult],
        pr_number: int,
        verified_accurate_count: int,
    ) -> ActionOutput:
        """
        Main entry point. Processes all repairs and posts results to GitHub.
        """
        fix_prs = []
        flagged = []
        autofix = []

        for repair in repairs:
            if repair.ready_for_pr:
                # High confidence — create a fix PR
                fix_pr_number = self._create_fix_pr(repair, pr_number)
                if fix_pr_number:
                    fix_prs.append(fix_pr_number)
                    autofix.append(repair)
            else:
                # Low confidence — flag for human review
                flagged.append(repair)

        # Post summary comment on the original PR
        comment_url = self._post_summary_comment(
            pr_number=pr_number,
            accurate_count=verified_accurate_count,
            autofix=autofix,
            flagged=flagged,
            fix_pr_numbers=fix_prs,
        )

        return ActionOutput(
            pr_number=pr_number,
            sections_checked=verified_accurate_count + len(autofix) + len(flagged),
            sections_accurate=verified_accurate_count,
            sections_autofix=len(autofix),
            sections_flagged=len(flagged),
            fix_pr_numbers=fix_prs,
            comment_url=comment_url,
        )

    def _create_fix_pr(self, repair: RepairResult, source_pr_number: int) -> int:
        """
        Creates a new branch with the corrected doc and opens a PR.
        Returns the new PR number, or None if it failed.
        """
        section = repair.verification.suspect
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        branch_name = f"doc-fix/{section.heading_path.replace(' ', '-').replace('>', '').lower()}-{timestamp}"
        branch_name = branch_name[:60]  # GitHub branch name length limit

        try:
            # Get the base branch (main or master)
            default_branch = self.repo.default_branch
            base_sha = self.repo.get_branch(default_branch).commit.sha

            # Create new branch
            print(f"[GitHub] Creating branch: {branch_name}")
            self.repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_sha,
            )

            # Get current file contents
            doc_file = self.repo.get_contents(section.file_path, ref=default_branch)

            # Replace the stale section with the corrected one
            updated_content = doc_file.decoded_content.decode("utf-8").replace(
                repair.original_content,
                repair.corrected_content,
            )

            # Commit the change
            commit_message = (
                f"docs: fix stale section '{section.heading_path}'\n\n"
                f"Auto-generated by self-healing docs action.\n"
                f"Triggered by changes to `{section.triggered_by.function_name}` "
                f"in PR #{source_pr_number}.\n\n"
                f"Diagnosis: {repair.verification.diagnosis}"
            )

            self.repo.update_file(
                path=section.file_path,
                message=commit_message,
                content=updated_content,
                sha=doc_file.sha,
                branch=branch_name,
            )

            # Open the PR
            pr_body = self._build_fix_pr_body(repair, source_pr_number)
            fix_pr = self.repo.create_pull(
                title=f"docs: fix stale section — {section.heading_path}",
                body=pr_body,
                head=branch_name,
                base=default_branch,
            )

            print(f"[GitHub] Created fix PR #{fix_pr.number}: {fix_pr.html_url}")
            return fix_pr.number

        except GithubException as e:
            print(f"[GitHub] Failed to create fix PR: {e}")
            return None

    def _post_summary_comment(
        self,
        pr_number: int,
        accurate_count: int,
        autofix: list[RepairResult],
        flagged: list[RepairResult],
        fix_pr_numbers: list[int],
    ) -> str:
        """
        Posts a summary comment on the original PR listing all results.
        """
        try:
            pr = self.repo.get_pull(pr_number)
            body = self._build_summary_comment(
                accurate_count, autofix, flagged, fix_pr_numbers
            )
            comment = pr.create_issue_comment(body)
            print(f"[GitHub] Posted summary comment: {comment.html_url}")
            return comment.html_url
        except GithubException as e:
            print(f"[GitHub] Failed to post summary comment: {e}")
            return ""

    def _build_fix_pr_body(
        self, repair: RepairResult, source_pr_number: int
    ) -> str:
        section = repair.verification.suspect
        change = section.triggered_by
        return f"""## 🔧 Auto-generated Documentation Fix

This PR was automatically generated by the **self-healing docs** action.

### What changed in the code

`{change.function_name}` in `{change.file_path}` was modified in PR #{source_pr_number}.

### Why the docs were stale

{repair.verification.diagnosis}

### What was fixed

**Section:** `{section.heading_path}`
**File:** `{section.file_path}`

<details>
<summary>View diff</summary>

**Before:**
{repair.original_content[:500]}

**After:**
{repair.corrected_content[:500]}

</details>

### Validation

- Confidence: **{repair.confidence_level.value}**
- Validation notes: {repair.validation_notes}

---
*Generated by self-healing-docs · [View action run](../../actions)*
"""

    def _build_summary_comment(
        self,
        accurate_count: int,
        autofix: list[RepairResult],
        flagged: list[RepairResult],
        fix_pr_numbers: list[int],
    ) -> str:
        lines = ["## 📄 Doc Check Results\n"]

        # Summary line
        total = accurate_count + len(autofix) + len(flagged)
        lines.append(f"Checked **{total}** documentation sections.\n")

        # Accurate sections
        if accurate_count:
            lines.append(f"✅ **{accurate_count}** section(s) verified accurate\n")

        # Auto-fixed sections
        if autofix:
            lines.append(f"🔧 **{len(autofix)}** section(s) auto-fixed\n")
            for i, repair in enumerate(autofix):
                pr_num = fix_pr_numbers[i] if i < len(fix_pr_numbers) else "?"
                lines.append(
                    f"  - `{repair.verification.suspect.heading_path}` "
                    f"→ see PR #{pr_num}\n"
                )

        # Flagged sections
        if flagged:
            lines.append(f"⚠️ **{len(flagged)}** section(s) flagged for human review\n")
            for repair in flagged:
                lines.append(
                    f"  - `{repair.verification.suspect.heading_path}` "
                    f"in `{repair.verification.suspect.file_path}`\n"
                    f"    > {repair.verification.diagnosis}\n"
                )

        # No issues
        if not autofix and not flagged:
            lines.append("🎉 All documentation is up to date!\n")

        lines.append(
            "\n---\n*Generated by [self-healing-docs](../../actions)*"
        )
        return "".join(lines)